### ISSUE TITLE
BS deployment: get AWS credentials from aws configure

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout-terraform#101]
**Problem**: for now for every deployment I need to put AWS credentials to `./group_vars/all.yml`. Meanwhile, I have preconfigured credentials with `aws configure`

**Solution**: if there are no `aws_access_key` and  `aws_secret_key` filled in the config, authentify from `aws configure` credentials if it possible.

**Comment by ArseniiPetrovich** [comment]
This one can be tricky, but I think I find the way.
What I propose is to use `default(omit)` to suppress variables if they are not set.
