### ISSUE TITLE
Some ENV variables are deleted with deployment script

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout-terraform#108]
`METADATA_CONTRACT` and `VALIDATORS_CONTRACT` env vars are deleted on every deployment of xDai BS instance with deployment script

**Comment by ArseniiPetrovich** [comment]
@vbaranov 
Have we seen this issue happen for the last deployments?

**Comment by vbaranov** [comment]
No, I didn’t see this issue happened with the latest deployment script in the past deployments. I am closing this. I will reopen if the issue appear again
