### ISSUE TITLE
The ability to repeat only deployment step

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout-terraform#115]
I have a question about Blockscout deployment automation:

Is it possible to repeat the only deployment step in case of the previous deployment was failed?
I want to skip building, uploading to S3 steps, that were done in the previous deployment try and just want to repeat the last deployment

**Comment by Lorune** [comment]
I ran into this myself earlier aswell, have a look at : https://docs.ansible.com/ansible/latest/user_guide/playbooks_startnstep.html

**Comment by ArseniiPetrovich** [comment]
Either Lorune's idea, or One can simply tag the necessary step and run the playbook with `-t <tag>` argument.

**Comment by vbaranov** [comment]
@ArseniiPetrovich if I will repeat from the deployment step will the script clear AWS environment from the assets of the previously failed deployment? I mean Auto-scaling group related to the failed deployment.

**Comment by vbaranov** [comment]
Ok, I've tried as described here
>https://docs.ansible.com/ansible/latest/user_guide/playbooks_startnstep.html

```
viktor$ ansible-playbook deploy_software.yml --start-at-task="Deploy Blockscout"

PLAY [Save config file] ******************************************************************

PLAY [Deploy BlockScout] *****************************************************************

PLAY RECAP *******************************************************************************
```

and the new deployment didn't start.

**Comment by ArseniiPetrovich** [comment]
> Ok, I've tried as described here
> 
> > https://docs.ansible.com/ansible/latest/user_guide/playbooks_startnstep.html
> 
> ```
> viktor$ ansible-playbook deploy_software.yml --start-at-task="Deploy Blockscout"
> 
> PLAY [Save config file] ******************************************************************
> 
> PLAY [Deploy BlockScout] *****************************************************************
> 
> PLAY RECAP *******************************************************************************
> ```
> 
> and the new deployment didn't start.

Just checked - this is a known limitation while using dynamic includes. We can fix it in new version, because we no longer need to put role in a loop there.

**Comment by ArseniiPetrovich** [comment]
> @ArseniiPetrovich if I will repeat from the deployment step will the script clear AWS environment from the assets of the previously failed deployment? I mean Auto-scaling group related to the failed deployment.

No, script is not designed to delete AWS ASG from failed deployment. I can come up with the idea on how to select the latest ASG from failed deployment, but can't understand in which cases this task should be executed.

**Comment by vbaranov** [comment]
The case is pretty simple:
We have a long DB migration in the update. The first deployment failed because migrations took longer than the defined timeout. We just need to repeat the same deployment (that already uploaded to AWS)

**Comment by ArseniiPetrovich** [comment]
I think we can tag the necessary steps with `redeploy` mark and use `ansible-playbook deploy_software.yml -t redeploy`.

**Comment by ArseniiPetrovich** [comment]
In #126 we have introduced and documented the 3 tags to cover different aspects of deployment - `build` server, `deploy` server and `update_vars` - for production variables.

**Comment by ArseniiPetrovich** [comment]
Using the same method as with the mentioned tags anyone could add the tags that will be suitable for their particular situation. Closing for now.
