### ISSUE TITLE
Don't update Parameters store var if it is not present in the config

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout-terraform#118]
When I have in the config, let's say, 1 env var to update in Parameters store, Blockscout deployment script updates all of the parameters, even that are not present in the `all.yml` config. Is it possible to update only those, that are present in `all.yml`? It will save more time on deployment.

**Comment by ArseniiPetrovich** [comment]
Yes, it is possible. Good idea, I'll prepare the PR
