### ISSUE TITLE
403 Error during websocket handshake when deployed behind ELB

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout-terraform#45]
The following error is displayed in the browser console when the application is deployed behind ELB:
`WebSocket connection to 'ws://sokaj-explorer-sokol-elb-1723354604.us-east-1.elb.amazonaws.com/socket/websocket?locale=en&vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403`

`journalctl` shows the following error:

```
Jul 27 17:36:00 ...[16337]: 17:36:00.450 [error] Could not check origin for Phoenix.Socket transport.
Jul 27 17:36:00 ...[16337]: This happens when you are attempting a socket connection to
Jul 27 17:36:00 ...[16337]: a different host than the one configured in your config/
Jul 27 17:36:00 ...[16337]: files. For example, in development the host is configured
Jul 27 17:36:00 ...[16337]: to "localhost" but you may be trying to access it from
Jul 27 17:36:00 ...[16337]: "127.0.0.1". To fix this issue, you may either:
Jul 27 17:36:00 ...[16337]: 1. update [url: [host: ...]] to your actual host in the
Jul 27 17:36:00 ...[16337]: config file for your current environment (recommended)
Jul 27 17:36:00 ...[16337]: 2. pass the :check_origin option when configuring your
Jul 27 17:36:00 ...[16337]: endpoint or when configuring the transport in your
Jul 27 17:36:00 ...[16337]: UserSocket module, explicitly outlining which origins
Jul 27 17:36:00 ...[16337]: are allowed:
Jul 27 17:36:00 ...[16337]: check_origin: ["https://example.com",
Jul 27 17:36:00 ...[16337]: "//another.com:888", "//other.com"]

```

**Comment by acravenho** [comment]
For this issue, we need an Application Load Balancer to handle WebSockets. Currently, we have a Classic Load Balancer

**Comment by acravenho** [comment]
@bitwalker How difficult would it be to implement an Application Load Balancer as opposed to a Classic Load Balancer?

**Comment by bitwalker** [comment]
@acravenho It should be pretty straightforward:

- Create an application load balancer resource
- Create a target group resource (configured with the _internal_ port and protocol, not end-user facing (that is handled by the ALB)
- Create an application load balancer listener resource, configured with the external port/protocol/etc.; configure it to use the target group resource created above
- Replace the use of `load_balancers` in the auto-scaling group resource with `target_group_arns`
- Change the CodeDeploy deployment config to use `target_group_info` rather than `elb_info`

I believe that should cover everything that needs to change

**Comment by acravenho** [comment]
@bitwalker Perfect. I'll give a try today manually and see if I run into any issues 👍

**Comment by bitwalker** [comment]
@acravenho You probably have already seen it, but if you want to know what options are available for each resource, you can find those docs [here](https://www.terraform.io/docs/providers/aws/r/lb.html)

**Comment by acravenho** [comment]
@bitwalker I've attempted it before using those docs but now that I have a more defined path I should be able to figure it out. Thank you for the help :)

**Comment by bitwalker** [comment]
No problem! And yeah, the ALB's have some more moving parts than the classic ELBs, so they are a bit trickier to figure out just from the docs - the target group thing is the main sticking point, once you've got that sorted, they start to feel more familiar

**Comment by acravenho** [comment]
Thanks for the help @bitwalker. Couldn't have done it without you.
