### ISSUE TITLE
(Mix) The task "phx.server" could not be found.

### ISSUE THREAD

**Issue by danbryan** [poanetwork/blockscout-terraform#55]
Hello, during deployment of blockscout-terraform on a fresh AWS account I noticed the web application was not starting.  I confirmed that the userdata was ran on the EC2 instance, the explorer.service was created, but the service will not start due to the error. "(Mix) The task "phx.server" could not be found."  I looked at the unit-file and it indicated:

````
WorkingDirectory=/opt/app
ExecStart=/opt/elixir/bin/mix phx.server
````

/opt/app was an empty folder, and i was not able to find the file phx.server anywhere on the local file system.  I was able to get blockscout working by manually installing it on the ec2 instance.  I followed the guide here. https://github.com/poanetwork/blockscout/blob/master/README.md  I would like to know if anyone else has encountered this error when trying to deploy blockscout via terraform.

**Comment by acravenho** [comment]
@danbryan Once you finish the deployment of `blockscout-terraform` you'll be prompted with instructions on how to deploy explorer. It will look similar to:

```
Outputs:

db_instance_address = tes31-poa.cdl6z46qyrxn.us-east-1.rds.amazonaws.com
instructions = To deploy a new version of the application manually:

    1) Run the following command to upload the application to S3.

        aws deploy push --application-name=tes31-explorer --s3-location s3://tes31-explorer-codedeploy-releases/path/to/release.zip --source=path/to/repo

    2) Follow the instructions in the output from the `aws deploy push` command
       to deploy the uploaded application. Use the deployment group names shown below:

        - tes31-explorer-dg0

       You will also need to specify a deployment config name. Example:

        --deployment-config-name=CodeDeployDefault.OneAtATime

       A deployment description is optional.

    3) Monitor the deployment using the deployment id returned by the `aws deploy create-deployment` command:

        aws deploy get-deployment --deployment-id=<deployment-id>

    4) Once the deployment is complete, you can access each chain explorer from its respective url:

        - sokol: tes31-explorer-sokol-alb-1037244414.us-east-1.elb.amazonaws.com
Infrastructure has been successfully provisioned!
```

In step one you upload a local copy of `blockscout` to an s3 bucket. Then you'll be prompted to start a deployment via CodeDeploy in AWS.

**Comment by danbryan** [comment]
Thanks, I'll give that a try! I noticed those instructions in the output, but for some reason when i saw the phrase "To deploy a new version of the application..." it made me think a current version was already installed, and this was only needed for newer versions.  Is there a reason the web app deploy cannot be provisioned by terraform?  Thanks again for the quick response.

**Comment by acravenho** [comment]
Great, please let me know if you need any further help. 

In the future, we're planning on letting terraform handle everything including deploying the explorer.
