### ISSUE TITLE
Add hostname to the ec2 instance to access observer

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout-terraform#61]
We need to be able to identify where certain chains are hanging. Observer is a great monitoring tool and needs to be accessed remotely. A hostname is required to accomplish this.

**Comment by phahulin** [comment]
`hostname` should be a new parameter set in terraform config.

**Comment by ArseniiPetrovich** [comment]
As far as I see the other monitoring tools are being used, so this is not valid anymore. 
@vbaranov ?

**Comment by vbaranov** [comment]
Yes, *wobserver* monitoring tool is used in Blockscout instances. I guess this issue is not relevant.
