### ISSUE TITLE
Add Prometheus and Grafana to cluster

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/blockscout-terraform#62]
Prometheus and Grafana have been added to blockscout in poanetwork/blockscout#841, but the Prometheus and Grafana servers need to be setup in the cluster and configured to talk to each other and the BlockScout `/metrics` endpoint.

**Comment by acravenho** [comment]
1. Setup EC2 instance of BlockScout (save endpoint to let Prometheus know where to listen /metrics)
2. Setup EC2 instance for Prometheus
3. Install Prometheus (look into the config step for `prometheus --config.file=prometheus.yml`)
4. Setup EC2 instance for Grafana 
5. Install grafana
6. Install Pie Chart panel plugin: grafana-cli plugins install grafana-piechart-panel
7. Start grafana: `systemctl start grafana.service`
8. Add Prometheus as a Data Source (most likely as a json file. where is this stored)
9. Add dashboards from https://github.com/deadtrickster/beam-dashboards

**Comment by acravenho** [comment]
This issue has been resolved internally by creating the instance manually. Multiple instances of BlockScout can be added to a single instance of Prometheus and Granfana.
