### ISSUE TITLE
Add SSL Certificate Environment Variables and Configure SSL on EC2

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout-terraform#81]
https://github.com/poanetwork/blockscout/pull/1365 enables HTTP/2. The production environment needs to add the following environment variables:
- SSL_CACERT_FILE
- SSL_CERT_FILE
- SSL_DHPARAM_FILE
- SSL_KEY_FILE

These need to be configured through LetsEncrypt or AWS cert infrastructure.

**Comment by KronicDeth** [comment]
Not needed when deployed behind ALB as it accepts HTTP/2 requests, but forwards them as HTTP/1.1 requests to Phoenix.  This would only be needed if/when ALB supports forwarding HTTP/2 requests to Phoenix.  HTTP/2 terminated at Phoenix would be nice as it would allow server-side push of assets.
