### ISSUE TITLE
Add `clean` command

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout-terraform#83]
Add `clean` command to `bin/infra` bash script, which will remove:
1. `.terraform` folder
2. `terraform.tfstate.d` folder
3. `main.tfvars`
4. `backend.tfvars`

It would be useful to clean the environment for starting a new terraform deployment

**Comment by ArseniiPetrovich** [comment]
I will add a `clean.yml` playbook with upcoming PR.
