### ISSUE TITLE
Default CIDR for DB subnet is wrong

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/blockscout-terraform#89]
```
variable "vpc_cidr" {
  description = "Virtual Private Cloud CIDR block"
  default     = "10.0.0.0/16"
}

variable "db_subnet_cidr" {
  description = "The CIDR block for the database subnet"
  default     = "10.0.1.0/16"
}
```
The following defaults are senseless, at least because 10.0.1.0/16 is equal to 10.0.0.0/16 and `vpc_cidr` contain public web network besides the DB network. I do believe that we should change this lines as follows:
```
variable "vpc_cidr" {
  description = "Virtual Private Cloud CIDR block"
  default     = "10.0.0.0/16"
}

variable "db_subnet_cidr" {
  description = "The CIDR block for the database subnet"
  default     = "10.0.1.0/24"
}
```

**Comment by ArseniiPetrovich** [comment]
Hm... It looks like the current process works, in contra to my idea. This is because cidrsubnet() function is used to split db_subnet_cidr into networks - one for each AZ. I believe we should still think about refactoring of this part of code to make it more... understandable.

**Comment by vbaranov** [comment]
@ArseniiPetrovich could we close it, as you implemented refactored Ansible playbooks, or you want to continue on this task?

**Comment by ArseniiPetrovich** [comment]
@vbaranov #90 doesn't cover this issue. It should remain opened for now.
