### ISSUE TITLE
Add variables validations

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout-terraform#93]
Inspired by this comment https://github.com/poanetwork/blockscout-terraform/pull/92#pullrequestreview-213876256

- [x] the chain length shouldn't be more 5 symbols
- [x] the prefix length should be 5 symbols

**Comment by ArseniiPetrovich** [comment]
Should prefix contain 5 symbols exact? We already have a check for this, but it checks for 3 to 5 symbols.

**Comment by vbaranov** [comment]
>We already have a check for this, but it checks for 3 to 5 symbols.

you're right. 3 to 5 is correct.
